apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.go-api.name }}-deployment
  namespace: {{ .Values.go-api.namespace }}
spec:
  replicas: {{ .Values.go-api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.go-api.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.go-api.name }}
    spec:
      containers:
      - image: {{ .Values.go-api.image.repository }}:{{ .Values.go-api.image.tag }}
        name: {{ .Values.go-api.name }}
        ports:
        - containerPort: {{ .Values.go-api.service.targetPort }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
