apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-go-api
  namespace: dev
spec:
  parentRefs:
  - name: demo-gateway
    namespace: envoy-gateway-system
    sectionName: http
  rules:
  - matches:
      - path:
          value: "/songs"
    backendRefs:
      - name: go-api-svc
        weight: 1
        port: 80