apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: go-api-route
spec:
  parentRefs:
    - name: eg
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /songs
      backendRefs:
        - name: go-api-svc 
          port: 8080