apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: 'docker-desktop-cluster/envoy-proxy-gateway'
    repoURL: 'git@github.com:marcobradley/k8s-docker-demo.git'
    targetRevision: 'main'
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true