apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  sources:
  - chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.7.0
    helm:
      valueFiles:
      - $values/docker-desktop-cluster/envoy-gateway/values.yaml
  - repoURL: git@github.com:marcobradley/k8s-docker-demo.git
    targetRevision: main
    ref: values
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true