apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  sources:
  - chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.7.0
    values:
      service:
        type: NodePort
        nodePorts:
          http: 30000
    path: 'docker-desktop-cluster/envoy-gateway'
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc