---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'demo-dev'
  namespace: argocd
spec:
  destination:
    namespace: 'dev'
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
    path: 'docker-desktop-cluster\k8s-demo'
    repoURL: 'git@github.com:marcobradley/k8s-docker-demo.git'
    targetRevision: 'main'
  sources: []
  project: 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true