---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: dev
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-app
status:
  loadBalancer: {}